// Generated Convex API declarations
export const api: any = {
  profiles: {
    getCurrentProfile: "profiles:getCurrentProfile",
    getProfileByClerkId: "profiles:getProfileByClerkId",
    getProfileByUsername: "profiles:getProfileByUsername",
    syncProfile: "profiles:syncProfile",
    updateProfile: "profiles:updateProfile",
    awardPoints: "profiles:awardPoints",
  },
  events: {
    listEvents: "events:listEvents",
    getEventBySlug: "events:getEventBySlug",
    getFeaturedEvent: "events:getFeaturedEvent",
    isUserRegistered: "events:isUserRegistered",
    registerForEvent: "events:registerForEvent",
    createEvent: "events:createEvent",
    updateEvent: "events:updateEvent",
    deleteEvent: "events:deleteEvent",
  },
  activities: {
    listActivitiesByEvent: "activities:listActivitiesByEvent",
    listActivitiesByEventSlug: "activities:listActivitiesByEventSlug",
    getActivityBySlug: "activities:getActivityBySlug",
    createActivity: "activities:createActivity",
  },
  matches: {
    getMatchByRoomCode: "matches:getMatchByRoomCode",
    getMatchById: "matches:getMatchById",
    createPrivateRoom: "matches:createPrivateRoom",
    joinPrivateRoom: "matches:joinPrivateRoom",
    findQuickMatch: "matches:findQuickMatch",
    setPlayerReady: "matches:setPlayerReady",
    pullRope: "matches:pullRope",
    startMatchNow: "matches:startMatchNow",
    listUserMatches: "matches:listUserMatches",
    listLiveMatches: "matches:listLiveMatches",
    terminateMatch: "matches:terminateMatch",
  },
  pookalam: {
    saveDraft: "pookalam:saveDraft",
    getUserDraft: "pookalam:getUserDraft",
    submitToCompetition: "pookalam:submitToCompetition",
    listGallery: "pookalam:listGallery",
    getSubmissionById: "pookalam:getSubmissionById",
    votePookalam: "pookalam:votePookalam",
    hasUserVoted: "pookalam:hasUserVoted",
    awardWinnerBadge: "pookalam:awardWinnerBadge",
    adminListSubmissions: "pookalam:adminListSubmissions",
  },
  quizzes: {
    getQuizBySlug: "quizzes:getQuizBySlug",
    getQuizQuestionsForPlayer: "quizzes:getQuizQuestionsForPlayer",
    startQuizSession: "quizzes:startQuizSession",
    submitAnswer: "quizzes:submitAnswer",
    adminAddQuestion: "quizzes:adminAddQuestion",
  },
  creators: {
    applyAsCreator: "creators:applyAsCreator",
    getMyApplication: "creators:getMyApplication",
    listApplicationsForAdmin: "creators:listApplicationsForAdmin",
    approveApplication: "creators:approveApplication",
    rejectApplication: "creators:rejectApplication",
    listVerifiedCreators: "creators:listVerifiedCreators",
    getCreatorByUsername: "creators:getCreatorByUsername",
  },
  leaderboards: {
    getGlobalLeaderboard: "leaderboards:getGlobalLeaderboard",
    getVadamvaliLeaderboard: "leaderboards:getVadamvaliLeaderboard",
    getQuizLeaderboard: "leaderboards:getQuizLeaderboard",
    getPookalamLeaderboard: "leaderboards:getPookalamLeaderboard",
    getMyRank: "leaderboards:getMyRank",
  },
  notifications: {
    listMyNotifications: "notifications:listMyNotifications",
    getUnreadCount: "notifications:getUnreadCount",
    markAsRead: "notifications:markAsRead",
    markAllAsRead: "notifications:markAllAsRead",
  },
  announcements: {
    listGlobalAnnouncements: "announcements:listGlobalAnnouncements",
    listEventAnnouncements: "announcements:listEventAnnouncements",
    publishAnnouncement: "announcements:publishAnnouncement",
  },
  admin: {
    getPlatformAnalytics: "admin:getPlatformAnalytics",
    listUsers: "admin:listUsers",
    updateUserRole: "admin:updateUserRole",
    toggleSuspension: "admin:toggleSuspension",
    listAuditLogs: "admin:listAuditLogs",
    bootstrapSuperAdmin: "admin:bootstrapSuperAdmin",
  },
  seed: {
    seedDatabase: "seed:seedDatabase",
  },
};

export const internal: any = api;
